from tkinter import*
tunniplaan=Tk()
Label(text="").grid(row=2, column=0)

Label(text="Esmaspäev").grid(row=0, column=0)
Label(text="").grid(row=2, column=1)
Button(text="Tugiõpe \nEesti keel").grid(row=1, column=1)
Button(text="Logistikateenused \nja varude juhtimine").grid(row=0, column=2)
Button(text="Logistikateenused \nja varude juhtimine").grid(row=1, column=2)
Button(text="Matemaa \ntika").grid(row=0, column=3)
Button(text="Matemaa \ntika").grid(row=1, column=3)
Button(text="Paus \nLõuna").grid(row=0, column=4)
Button(text="Paus \nLõuna").grid(row=1, column=4)
Button(text="Keel ja \nkirjandus").grid(row=0, column=4)
Button(text="Keel ja \nkirjandus").grid(row=1, column=4)
Button(text="Tugiõpe \n(matemaatika)").grid(row=0, column=4)
Button(text="Tugiõpe \n(matemaatika)").grid(row=1, column=4)

Label(text="Teisipäev").grid(row=2, column=0)
Label(text="").grid(row=3, column=0)
Button(text="Tugiõpe \n(keemia)").grid(row=2, column=1)
Button(text="Tugiõpe \n(keemia)").grid(row=3, column=1)
Button(text="Programmeerimise alused \n(eesti keeles)").grid(row=2, column=2)
Button(text="Programmeerimise alused \n(eesti keeles)").grid(row=3, column=2)
Button(text="Paus \nLõuna").grid(row=2, column=3)
Button(text="Paus \nLõuna").grid(row=3, column=3)
Button(text="Füüsika\n").grid(row=2, column=4)
Button(text="Füüsika\n").grid(row=3, column=4)

Label(text="Kolmapäev").grid(row=4, column=0)
Label(text="").grid(row=5, column=0)
Button(text="Tugiõpe \nEesti keel").grid(row=4, column=1)
Button(text="Kunstiained \n(eesti keeles)").grid(row=4, column=2)
Button(text="Kunstiained \n(eesti keeles)").grid(row=5, column=2)
Button(text="Paus \nLõuna").grid(row=4, column=3)
Button(text="Paus \nLõuna").grid(row=5, column=3)
Button(text="Kehaline \nKasvatus").grid(row=4, column=4)
Button(text="Kehaline \nKasvatus").grid(row=5, column=4)

Label(text="Neljapäev").grid(row=6, column=0)
Label(text="").grid(row=7, column=0)
Button(text="Logistikateenused \nja varude juhtimine").grid(row=6, column=1)
Button(text="Logistikateenused \nja varude juhtimine").grid(row=7, column=1)
Button(text="Paus \nLõuna").grid(row=6, column=2)
Button(text="Paus \nLõuna").grid(row=7, column=2)
Button(text="Programmeerimise alused \n(eesti keeles)").grid(row=6, column=3)
Button(text="Programmeerimise alused \n(eesti keeles)").grid(row=7, column=3)
Button(text="Inglise \nkeel").grid(row=6, column=4)
Button(text="Rakenduskeskonna ja arenduskeskkonna \nloomine IT valdkonna").grid(row=7, column=4)
Button(text="Rakenduskeskonna ja arenduskeskkonna \nloomine IT valdkonna").grid(row=6, column=5)
Button(text="Eesti \nkeel").grid(row=7, column=5)

Label(text="Reede").grid(row=8, column=0)
Label(text="").grid(row=9, column=0)
Button(text="Rakenduskeskonna ja arenduskeskkonna \nloomine IT valdkonna").grid(row=9, column=1)
Button(text="Eesti \nkeel").grid(row=8, column=1)
Button(text="Programmeerimise alused \n(eesti keeles)").grid(row=8, column=2)
Button(text="Programmeerimise alused \n(eesti keeles)").grid(row=9, column=2)
Button(text="Rakenduskeskonna ja arenduskeskkonna \nloomine IT valdkonna").grid(row=8, column=3)
Button(text="Inglise \nkeel").grid(row=9, column=3)
tunniplaan.mainloop()